version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: credit-card-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: credit_card_recommender
    volumes:
      - mongodb_data:/data/db
    networks:
      - credit-card-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: credit-card-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/credit_card_recommender?authSource=admin
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - credit-card-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: credit-card-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - credit-card-network

volumes:
  mongodb_data:

networks:
  credit-card-network:
    driver: bridge